baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Rain’s Blog"
theme = "PaperMod"

[params]
  author = "Rain Si"
  defaultTheme = "auto"  # 自动切换深浅模式
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

